### PR TITLE
Added new file Jmd_SS_Test_3

### PR DESCRIPTION
**Pull request by sanjeevgit1234**
Hi Nna
Jmd_SS_Test_3, new file added
Thanks
SS

### CODE REVIEW

**Comment by Nna1234** [comment]
Hi SS
looks good but need 2 more lines Jmd_SS_test_3

**Comment by sanjeevgit1234** [comment]
Hi Nna
2 more lines added as per your instruction
pl review it
Thanks
SS

**Comment by sanjeevgit1234** [comment]
Hi NNa 
again added codes in Jmd_SS_Test_3

**Comment by Nna1234** [comment]
ok 
merge to master

**Pull request merged**
